argonaut:
  work-directory: ''
  dacs:
    - name: aoml
#      email:
#        - foo.bar@example.com
  index-cron: '0 * * * * ?'
  gdac-sync-cron: '30 3 * * * ?'
  float-merge-quiet-timeout: 'PT30M'
  file-checker-timeout: 'PT2M'
  validation-threads: 20
  file-checker-heap: '256m'
  submission-report-threads: 10
  local-submission-ftp-server:
    enabled: false
    password-encoding: sha256
    user-file: '${svc.home}/config/ftp-server-users.properties'
    keystore-file: '${svc.home}/config/ftp-server.jks'
    keystore-password: ''
    port: 2221
    anonymous-login-enabled: false
  local-output-ftp-server:
    enabled: false
    password-encoding: sha256
    user-file: '${svc.home}/config/ftp-anonymous.properties'
    keystore-file: '${svc.home}/config/ftp-server.jks'
    keystore-password: ''
    port: 2211
    anonymous-login-enabled: true
  output-directory: ''

server:
  compression:
    enabled: true
  tomcat:
    redirect-context-root: false
    use-relative-redirects: true
    accesslog:
      directory: ${svc.home}/log
      enabled: true
      max-days: 31
  port: 4747
  ssl:
    enabled: true
    #key-store: ''
    #key-store-password: ''
    key-store-type: PKCS12
    #key-alias: ''
  servlet:
    context-path: /gdac

camel:
  springboot:
    main-run-controller: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  web:
    resources:
      static-locations:
        - file:${argonaut.output-directory}/
        - classpath:/static/
  main:
    web-application-type: none
  threads:
    virtual:
      enabled: true

