<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.github.ci-cmg.argo</groupId>
    <artifactId>argonaut-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>

  <artifactId>argonaut-postgres</artifactId>

  <properties>
    <project.root>${project.parent.basedir}</project.root>
    <docker.logStdout>true</docker.logStdout>
    <docker.verbose>true</docker.verbose>
    <docker.showLogs>true</docker.showLogs>
  </properties>

  <dependencies>
    <dependency>
      <groupId>jakarta.persistence</groupId>
      <artifactId>jakarta.persistence-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.hibernate.orm</groupId>
      <artifactId>hibernate-core</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.hibernate.orm</groupId>
      <artifactId>hibernate-spatial</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.locationtech.jts</groupId>
      <artifactId>jts-core</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
      <exclusions>
        <exclusion>
          <artifactId>spring-boot-starter-logging</artifactId>
          <groupId>org.springframework.boot</groupId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.apache.camel</groupId>
      <artifactId>camel-test-spring-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-simple</artifactId>
      <scope>test</scope>
    </dependency>

  </dependencies>


  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <annotationProcessorPath>
              <groupId>org.hibernate</groupId>
              <artifactId>hibernate-jpamodelgen</artifactId>
              <version>${hibernate.version}</version>
            </annotationProcessorPath>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
    </plugins>
  </build>


  <profiles>
    <profile>
      <id>it</id>
      <build>
        <plugins>
          <plugin>
            <groupId>io.fabric8</groupId>
            <artifactId>docker-maven-plugin</artifactId>
            <version>0.40.2</version>
            <configuration>
              <images>
                <image>
                  <name>postgis/postgis:15-3.4</name>
                  <alias>it-database</alias>
                  <run>
                    <env>
                      <POSTGRES_USER>argonaut</POSTGRES_USER>
                      <POSTGRES_PASSWORD>letmein</POSTGRES_PASSWORD>
                    </env>
                    <ports>
                      <port>15437:5432</port>
                    </ports>
                    <ulimits>
                      <ulimit>
                        <name>nofile</name>
                        <hard>1048576</hard>
                        <soft>1048576</soft>
                      </ulimit>
                    </ulimits>
                    <privileged>true</privileged>
                    <wait>
                      <tcp>
                        <ports>
                          <port>15437</port>
                        </ports>
                      </tcp>
                      <log>.*\[1\] LOG: database system is ready to accept connections</log>
                      <time>60000</time>
                    </wait>
                  </run>
                </image>
              </images>
            </configuration>
            <executions>
              <execution>
                <id>prepare-it-database</id>
                <phase>pre-integration-test</phase>
                <goals>
                  <goal>start</goal>
                </goals>
              </execution>
              <execution>
                <id>remove-it-database</id>
                <phase>post-integration-test</phase>
                <goals>
                  <goal>stop</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.apache.maven.plugins</groupId>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>3.5.4</version>
            <executions>
              <execution>
                <id>integration-test</id>
                <goals>
                  <goal>integration-test</goal>
                </goals>
              </execution>
              <execution>
                <id>verify</id>
                <goals>
                  <goal>verify</goal>
                </goals>
              </execution>
            </executions>
          </plugin>
          <plugin>
            <groupId>org.flywaydb</groupId>
            <artifactId>flyway-maven-plugin</artifactId>
            <version>10.19.0</version>
            <dependencies>
              <dependency>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-database-postgresql</artifactId>
                <version>10.19.0</version>
              </dependency>
            </dependencies>
            <executions>
              <execution>
                <id>migrate-schema</id>
                <phase>pre-integration-test</phase>
                <goals>
                  <goal>migrate</goal>
                </goals>
              </execution>
            </executions>
            <configuration>
              <url>jdbc:postgresql://localhost:15437/argonaut</url>
              <user>argonaut</user>
              <password>letmein</password>
              <locations>
                <location>classpath:edu/colorado/cires/argonaut/postgres/migration</location>
              </locations>
              <placeholders>
                <schema_name>public</schema_name>
              </placeholders>
              <baselineOnMigrate>true</baselineOnMigrate>
              <schemas>
                <schema>
                  public
                </schema>
              </schemas>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>

</project>