dac.submission.directory=
dac.processing.directory=
dac.output.directory=
dac.index.database-file=
dac.audit.database-file=
work-directory=
gdac-institution=

float-merge.enabled=true
float-merge.page-size=200
float-merge.cron=0 0/30 * * * ?

synthetic-profile.enabled=true
synthetic-profile.page-size=200
synthetic-profile.cron=0 0/30 * * * ?

file-check.use-online-nvs=false
file-check.do-nulls=false
file-check.do-format-only=false
file-check.do-name-check=true
file-check.do-psal-stats=false
file-check.do-format-only-pre-31=true