dac.submission.directory=
dac.processing.directory=
dac.output.directory=
dac.submission.database-file=
dac.submission.report.cron=0 0/10 * * * ?
work-directory=

float-merge.enabled=true
float-merge.page-size=200
float-merge.cron=0 0/30 * * * ?

synthetic-profile.enabled=true
synthetic-profile.page-size=200
synthetic-profile.cron=0 0/30 * * * ?