name: maven build

on:
  push:
    branches: [ "trunk", "[0-9]+.[0-9]+" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: build with maven
        run: mvn -B -s settings.xml clean deploy -DskipTests
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
          SIGN_KEY_PASS: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
          SIGN_KEY: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
      - id: version
        run: |
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"
          echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_ENV"
      - name: Upload Zip
        uses: actions/upload-artifact@v4
        with:
          name: zip
          path: "argonaut-example/argonaut-simple/target/argonaut-simple-${{ env.version }}.zip"
      - name: Upload Tar.gz
        uses: actions/upload-artifact@v4
        with:
          name: targz
          path: "argonaut-example/argonaut-simple/target/argonaut-simple-${{ env.version }}.tar.gz"
  release:
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
      - run: mkdir release
      - run: cp zip/* release/argonaut-simple-${{ needs.build.outputs.version }}.zip
      - run: cp targz/* release/argonaut-simple-${{ needs.build.outputs.version }}.tar.gz
      - name: Update branch release
        uses: eine/tip@master
        with:
          tag: '${{ github.ref_name  }}-latest'
          rm: true
          token: ${{ secrets.RELEASE_PAT }}
          files: release/*